sudo: required
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: COMMAND="sudo npm install -g appium-chromedriver"
    - os: osx
      osx_image: xcode10
      sudo: required
      env: COMMAND="npm test"
    - os: osx
      osx_image: xcode10
      sudo: required
      env: COMMAND="npm run e2e-test" _FORCE_LOGS=1
language: node_js
node_js: "8"
before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      wget -P /tmp/ https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg;
      hdiutil attach /tmp/googlechrome.dmg;
      sudo cp -r /Volumes/Google\ Chrome/Google\ Chrome.app /Applications/;
    fi
before_script:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then npm run chromedriver; fi
script:
  - $COMMAND
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo npm install -g appium-chromedriver; fi
after_success:
  - npm run coverage
